### PR TITLE
Remove dividers in compact view

### PR DESCRIPTION
**Pull request by xmrv**
Side by side comparison of suggested change:

aegis-comp

### CODE REVIEW

**Comment by alexbakker** [comment]
Thanks for submitting your patch for this. As said on Matrix though, we're not sure about this one yet. So we'll leave this open for now.

**Comment by ipkpjersi** [comment]
I prefer the dividers FWIW.

**Comment by prophet6250** [comment]
This would certainly make much more sense. Can we know why we're not sure about adding this patch @alexbakker ?

**Comment by alexbakker** [comment]
@prophet6250 Sure, because some people prefer the dividers. See the comment right above yours.

**Comment by Sami32** [comment]
I prefer with the dividers as well.

**Comment by michaelschattgen** [comment]
We appreciate the effort but I'm closing this as we currently prefer the dividers. Please hold off on making pull requests until a proposal has been accepted, we don't like rejecting them.

**Pull request closed without merging**
