### PR TITLE
Introducing Arabic support

### PR DESCRIPTION
**Pull request by nourserry**
Initial Arabic language support,
All strings translated.

### CODE REVIEW

**Comment by nourserry** [comment]
Can you please clarify which strings to remove?

> Thanks for translating Aegis! I see that you included some non-translatable strings into your translation file. Could you remove those?

Can you please clarify which strings to remove?

**Comment by alexbakker** [comment]
The ones with ``translatable="false"`` annotation.

**Comment by nourserry** [comment]
> The ones with `translatable="false"` annotation.

Oh, I honestly thought I should just leave those intact :sweat_smile:, will update the file right now.

**Comment by alexbakker** [comment]
Could you squash you changes into a single commit?

**Comment by nourserry** [comment]
Squashing is beyond my knowledge of git at the moment, I deleted the current fork as I missed up something,
Will submit a proper PR later today.

**Pull request closed without merging**
