### PR TITLE
Preserve backwards compatibility with Android < 7.0

### LINKED ISSUE #520: QR code reader got broken on older Android versions since commit c65ed16
###### Info

* __Version__: "1.2-beta4-c65ed16 (HEAD)" and later
* __Source__: GitHub
* __Vault encrypted:__ No
* __Device:__ Any (physical phone or emulator with old Android)
* __Android version and ROM:__ 5.0, 5.1, 6.0

###### Steps to reproduce

Open QR Scanner or Scan Image and feed it with a valid QR Code

###### What do you expect to happen?

The code should be scanned

###### What happens instead?

Aegis crashes with the "Unfortunately, Aegis has stopped" message and returns back to the account list instead of adding the code. Entering the code manually works as usual and is not affected.

###### Log

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.beemdevelopment.aegis.debug, PID: 3851
    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:57)
        at com.beemdevelopment.aegis.ui.MainActivity.onScanImageResult(MainActivity.java:305)
        at com.beemdevelopment.aegis.ui.MainActivity.onActivityResult(MainActivity.java:189)
        at android.app.Activity.dispatchActivityResult(Activity.java:6192)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3575)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3622)
        at android.app.ActivityThread.access$1300(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5305)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Got broken in this commit: c65ed167903f2075c5a536ebb1af63067034e328

### PR DESCRIPTION
**Pull request by SagePtr**
Fixes #520 <s>by downgrading com.google.zxing package to 3.3.3 (in 3.4.0 they dropped support of older Androids which are still widely used worldwide)</s> by adding desugaring for some features used in com.google.zxing

### CODE REVIEW

**Comment by alexbakker** [comment]
Thanks for reporting and picking this up. I'm unable to test this, as I can't reproduce the crash in an emulator, but I'll take your word for it. I think we may be able to fix this issue in a different way by enabling desugaring: https://developer.android.com/studio/write/java8-support#library-desugaring. That way, we don't have to downgrade to an older version of ZXing. Could you try that?

**Comment by SagePtr** [comment]
> I think we may be able to fix this issue in a different way by enabling desugaring.
Nice idea, desugaring worked without problems on my physical Android 5.1. I'm going to test it on different emulators and different Android versions to ensure it is sufficient for the fix.

**Comment by SagePtr** [comment]
Looks like desugaring is enough for work, works on API versions 21, 22, 23 without problems, so they didn't add more incompatible API-specific changes rather than language changes

**Comment by alexbakker** [comment]
Thanks!

**Pull request merged**
