### PR TITLE
Add entries showing count

### PR DESCRIPTION
**Pull request by orange-elephant**
#704
<p float="left">
  
  
</p>

### CODE REVIEW

**Comment by orange-elephant** [comment]
Converting to draft as I ran into odd looking padding when the groups chip is invisible.

**Comment by alexbakker** [comment]
Thanks for working on this!

While functionally this is fine, it's currently a bit too prominently placed on the main view. @michaelschattgen and I discussed this and he suggested the following: A better place for this might be all the way at the bottom of the entry list, fairly small, centered and in grey. If you have a bunch of entries, you'll have to scroll down to see it, but we think this isn't something you'd constantly be looking at anyway.

**Comment by orange-elephant** [comment]
Ill look at doing that next week. From what I can tell this will require modifying the EntryAdapter to allow multiple ViewHolder types  to put this into the RecyclerView as a footer. This would probably also be useful for implementing #983 to add pinned/ unpinned headers to the list.
That is unless you can think of a simpler solution I'm missing.

**Comment by alexbakker** [comment]
Yeah, that sounds like the right approach. I wonder if there'd be a way to pin that entry count view to the bottom in case you have just a few entries that only take up half of the screen.

**Comment by orange-elephant** [comment]
> I wonder if there'd be a way to pin that entry count view

In my opinion it is now subtle enough to look ok directly below the entries but let me know what you think

<p float="left">
  
  
</p>

**Review by alexbakker — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
