### PR TITLE
Create checkboxes dropdown component

### PR DESCRIPTION
**Pull request by orange-elephant**
As the groundwork for adding to multiple groups and to improve the existing multi-group selection in exports

<p float="left">
  
  
</p>

### CODE REVIEW

**Comment by alexbakker** [comment]
Functionally, this looks good to me. Visually this looks a little bit out of place unfortunately. Preferably we'd have something with a similar style as the "Export format" dropdown. I think ``MultiAutoCompleteTextView`` is what we're looking for, but I don't know if material components has a style for it and if it's easy to embed checkboxes as items.

I think this is an improvement over what we currently have for the export dialog though, so I'll leave it up to you if you want to spend time trying to make this work with ``MultiAutoCompleteTextView``. I think that work will be necessary if we want this to look nice in the entry editing view once we add support for having entries in multiple groups. For now I'd also be fine with merging this as is though.

**Comment by orange-elephant** [comment]
I'm happy to keep improving this, I managed to get it working with the Autocomplete TextView tonight. Currently you can use this view to search for groups you want to export, let me know what you think. Will sort out the styling next week

<p float="left">
  
  
</p>

**Comment by orange-elephant** [comment]
Personally I much prefer this approach, showing the number of groups selected with filtering disabled. This sort of component needs to implement the Filterable interface anyway so I could have it so the component is capable of both depending on what its used for, if you think there would be any benefit

<p float="left">
  
</p>

**Comment by alexbakker** [comment]
Agreed, that looks good! I'll have some time for a more in-depth look later this week.

> This sort of component needs to implement the Filterable interface anyway so I could have it so the component is capable of both depending on what its used for, if you think there would be any benefit

Sounds good to me.

**Review by alexbakker — APPROVED** [review]
Thanks!

**Pull request merged**
