### PR TITLE
Migrate Button To Material Design in Share Entry Class

### PR DESCRIPTION
**Pull request by Hacker437**
The shareEntry Class uses AppCompat Button I have Migrated to Material Button and adjusted the title and description above the QR Code

### CODE REVIEW

**Comment by Hacker437** [comment]
I Will Post Screen Shots

**Comment by Hacker437** [comment]
These Screenshots are for the commit #81587da
Old Group Dialog
Screenshot_20210830-190722
Screenshot_20210830-190711


New Dialog with button alignment and new styled chips
Screenshot_20210830-190552
Screenshot_20210830-190626

**Comment by alexbakker** [comment]
Could you split off the unrelated chip changes into a separate pull request? That would make it easier for us to review your work.

**Comment by Hacker437** [comment]
@alexbakker Like migration of buttons as one request and chips as one pull request

**Comment by alexbakker** [comment]
@Hacker437 Yes, exactly.

**Comment by Hacker437** [comment]
@alexbakker I am Sorry but how can I make that? Close this request and make 2 pull requests,The only way I know not familiar with GIT

**Comment by alexbakker** [comment]
@Hacker437 I would drop a17838a60e3228c31a840dc6d27a32624c1a53b5 from this pull request and force push to your branch. Then create a new pull request for the chip changes. If you're not familiar with Git yet, I'd recommend you read up on the basics (particularly branches, squashing and rebasing) and practice a bit. It'll make contributing to projects much easier.

**Comment by Hacker437** [comment]
> @Hacker437 I would drop [a17838a](https://github.com/beemdevelopment/Aegis/commit/a17838a60e3228c31a840dc6d27a32624c1a53b5) from this pull request and force push to your branch. Then create a new pull request for the chip changes. If you're not familiar with Git yet, I'd recommend you read up on the basics (particularly branches, squashing and rebasing) and practice a bit. It'll make contributing to projects much easier.

Ohh Thank You

**Comment by Hacker437** [comment]
I am Sorry for now I will learn git cherry picking.In the mean time I will open another pull requests

**Pull request closed without merging**
