### PR TITLE
Add Dutch translations

### PR DESCRIPTION
**Pull request by zaggo0**
Also added the ability to translate preference group titles

### CODE REVIEW

**Comment by alexbakker** [comment]
Thanks for the translation! Looks good to me from a quick glance.

The commit history looks a bit odd though. Can you remove the merge commit? On your branch, this should do the trick:

```
git rebase c5fa40166f4939d7bb2182cabe812e412f119f5d
git push -f
```

Next time, please rebase your work on master instead of merging master into your branch.

**Comment by zaggo0** [comment]
Alright, thanks! Didn't knew exactly how that worked, hehe. Should be good now, I think?

**Comment by michaelschattgen** [comment]
Thanks for your contribution! I've sent you a file with some minor text changes we would like to see.

After these fixes we will merge your pull request.

**Comment by michaelschattgen** [comment]
And we would really appreciate it if you could squash your commits so our git history won't be a mess.

Please let me know if you have any questions. Thanks!

**Pull request merged**
