### PR TITLE
Add selection indicator to ListItem

### PR DESCRIPTION
**Pull request by orangenbaumblatt**
Attempt to add an indicator to selected items like mentioned in #335.

Problems while implementing:

1. Flickering of indicator when scrolling. Seems to be related to the RecyclerView.
2. Animations work when selected/deselecting single items, but when using the back button the indicators just disappear without the animation.

Further ideas:

- Add color to `colors.xml` or choose an existing one
- Change the animation to a flip, like in Gmail

### CODE REVIEW

**Comment by michaelschattgen** [comment]
Nice work! Unfortunately the indicator is giving me some really strange visual bugs:
https://schattgen.nl/v/LordStarknakedTamp

If you look closely you'll see the indicator animation on every single item when scrolling, after scrolling back to the initial selected entries it sometimes forget to show the indicator. Is this something you can fix?

Besides that I think a darker shade of blue (or maybe red as @alexbakker suggested) will look a lot better and the animation needs to be a bit faster.

**Comment by orangenbaumblatt** [comment]
> Nice work! Unfortunately the indicator is giving me some really strange visual bugs:
> https://schattgen.nl/v/LordStarknakedTamp

It's exactly what I mean. Sadly I don't have much experience with Android frontend development, so I first have to take a deeper look into it to fix it.

In the meantime we could already add the lighter background color to have a fix for #335.

**Comment by orangenbaumblatt** [comment]
I think I was able to fix the flickering, but the back button still causes problems.
Does anyone have an idea?

**Comment by alexbakker** [comment]
This is still not quite right, but that's not your fault. This code has gotten really complex over time and I want to spare you the effort of trying to find all of the edge cases. I've prepared [a patch](https://alexbakker.me/u/ia0403p6py.patch) that you can apply to your PR. It should fix the remaining issues (including the back button animation). It also changes the color (again) and makes the animation duration a bit shorter.

```diff
diff --git a/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java b/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
index ac448fa..4777c8c 100644
--- a/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
+++ b/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryAdapter.java
@@ -304,12 +304,12 @@ public class EntryAdapter extends RecyclerView.Adapter<EntryHolder> implements I
     @Override
     public void onBindViewHolder(final EntryHolder holder, int position) {
         VaultEntry entry = _shownEntries.get(position);
-        holder.setFocused(_selectedEntries.contains(entry));
 
         boolean hidden = _tapToReveal && entry != _focusedEntry;
         boolean dimmed = _highlightEntry && _focusedEntry != null && _focusedEntry != entry;
         boolean showProgress = !isPeriodUniform() && entry.getInfo() instanceof TotpInfo;
         holder.setData(entry, _showAccountName, showProgress, hidden, dimmed);
+        holder.setFocused(_selectedEntries.contains(entry));
         holder.loadIcon(_view);
 
         holder.itemView.setOnClickListener(new View.OnClickListener() {
@@ -462,20 +462,26 @@ public class EntryAdapter extends RecyclerView.Adapter<EntryHolder> implements I
     }
 
     public void addSelectedEntry(VaultEntry entry) {
-        if (entry == null) {
-            for (VaultEntry vaultEntry: _selectedEntries) {
-                notifyItemChanged(_shownEntries.indexOf(vaultEntry));
-            }
-
-            _selectedEntries.clear();
-            return;
-        } else if (_highlightEntry) {
+        if (_highlightEntry) {
             resetFocus();
         }
 
         _selectedEntries.add(entry);
     }
 
+    public void deselectAllEntries() {
+        for (VaultEntry entry: _selectedEntries) {
+            for (EntryHolder holder : _holders) {
+                if (holder.getEntry() == entry) {
+                    holder.setFocusedAndAnimate(false);
+                    break;
+                }
+            }
+        }
+
+        _selectedEntries.clear();
+    }
+
     public boolean isDragAndDropAllowed() {
         return _sortCategory == SortCategory.CUSTOM && _groupFilter == null && _searchFilter == null;
     }
diff --git a/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java b/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
index 6360adc..e6a16c4 100644
--- a/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
+++ b/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryHolder.java
@@ -1,6 +1,7 @@
 package com.beemdevelopment.aegis.ui.views;
 
 import android.graphics.PorterDuff;
+import android.os.Handler;
 import android.view.View;
 import android.view.animation.Animation;
 import android.view.animation.AnimationUtils;
@@ -34,6 +35,7 @@ public class EntryHolder extends RecyclerView.ViewHolder {
     private VaultEntry _entry;
     private ImageView _buttonRefresh;
     private final ImageView _selected;
+    private final Handler _selectedHandler;
 
     private boolean _hidden;
 
@@ -56,6 +58,7 @@ public class EntryHolder extends RecyclerView.ViewHolder {
         _profileDrawable = view.findViewById(R.id.ivTextDrawable);
         _buttonRefresh = view.findViewById(R.id.buttonRefresh);
         _selected = view.findViewById(R.id.ivSelected);
+        _selectedHandler = new Handler();
 
         _progressBar = view.findViewById(R.id.progressBar);
         int primaryColorId = view.getContext().getResources().getColor(R.color.colorPrimary);
@@ -86,6 +89,10 @@ public class EntryHolder extends RecyclerView.ViewHolder {
         _entry = entry;
         _hidden = hidden;
 
+        _selected.clearAnimation();
+        _selected.setVisibility(View.GONE);
+        _selectedHandler.removeCallbacksAndMessages(null);
+
         // only show the progress bar if there is no uniform period and the entry type is TotpInfo
         setShowProgress(showProgress);
 
@@ -149,6 +156,7 @@ public class EntryHolder extends RecyclerView.ViewHolder {
 
     public void setFocused(boolean focused) {
         if (focused) {
+            _selected.setVisibility(View.VISIBLE);
             _view.setBackgroundColor(ThemeHelper.getThemeColor(R.attr.cardBackgroundFocused, _view.getContext().getTheme()));
         } else {
             _view.setBackgroundColor(ThemeHelper.getThemeColor(R.attr.cardBackground, _view.getContext().getTheme()));
@@ -160,11 +168,10 @@ public class EntryHolder extends RecyclerView.ViewHolder {
         setFocused(focused);
 
         if (focused) {
-            _selected.setVisibility(View.VISIBLE);
             _selected.startAnimation(_scaleIn);
         } else {
             _selected.startAnimation(_scaleOut);
-            _selected.postDelayed(() -> _selected.setVisibility(View.GONE), 250);
+            _selectedHandler.postDelayed(() -> _selected.setVisibility(View.GONE), 150);
         }
     }
 
diff --git a/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java b/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
index 5b40119..17c8e8f 100644
--- a/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
+++ b/app/src/main/java/com/beemdevelopment/aegis/ui/views/EntryListView.java
@@ -139,7 +139,12 @@ public class EntryListView extends Fragment implements EntryAdapter.Listener {
     public void setActionModeState(boolean enabled, VaultEntry entry) {
         _touchCallback.setSelectedEntry(entry);
         _touchCallback.setIsLongPressDragEnabled(enabled && _adapter.isDragAndDropAllowed());
-        _adapter.addSelectedEntry(entry);
+
+        if (enabled) {
+            _adapter.addSelectedEntry(entry);
+        } else {
+            _adapter.deselectAllEntries();
+        }
     }
 
     public void setSortCategory(SortCategory sortCategory, boolean apply) {
diff --git a/app/src/main/res/anim/item_scale_in.xml b/app/src/main/res/anim/item_scale_in.xml
index 2cf4934..d3aedbb 100644
--- a/app/src/main/res/anim/item_scale_in.xml
+++ b/app/src/main/res/anim/item_scale_in.xml
@@ -1,5 +1,5 @@
 <set xmlns:android="http://schemas.android.com/apk/res/android"
-    android:duration="250">
+    android:duration="150">
 
     <scale
         android:fromXScale="0"
diff --git a/app/src/main/res/anim/item_scale_out.xml b/app/src/main/res/anim/item_scale_out.xml
index adbda67..4392b73 100644
--- a/app/src/main/res/anim/item_scale_out.xml
+++ b/app/src/main/res/anim/item_scale_out.xml
@@ -1,5 +1,5 @@
 <set xmlns:android="http://schemas.android.com/apk/res/android"
-    android:duration="250">
+    android:duration="150">
 
     <scale
         android:fromXScale="100%"
diff --git a/app/src/main/res/layout/card_entry.xml b/app/src/main/res/layout/card_entry.xml
index 18479be..3f3fdd6 100644
--- a/app/src/main/res/layout/card_entry.xml
+++ b/app/src/main/res/layout/card_entry.xml
@@ -41,7 +41,7 @@
                 android:layout_centerVertical="true"
                 android:src="@drawable/item_selected"
                 android:visibility="gone"
-                app:civ_circle_background_color="@color/secondary_text_dark" />
+                app:civ_circle_background_color="@color/colorSecondary" />
         </RelativeLayout>
 
         <RelativeLayout

```

**Comment by orangenbaumblatt** [comment]
Thanks a lot for your help with this! It's definitely helping me getting better with Android development.
Applied the patch and pushed it to my branch.

**Comment by alexbakker** [comment]
No problem! There's one last thing I forgot about. We have different cards for the compact and small view modes: ``card_entry_compact`` and ``card_entry_small``. Those need the ``CircleImageView`` as well.

**Comment by orangenbaumblatt** [comment]
Totally forgot about those modes. Took care of them in the latest commit.

**Comment by alexbakker** [comment]
Oof, and now there's a minor conflict because of today's merges :(

**Comment by orangenbaumblatt** [comment]
Have resolved it really quickly. Some variables collided in `EntryHolder.java`.

**Comment by alexbakker** [comment]
Thanks a lot! Resolving the merge conflict introduced a merge commit. I squashed it away.

**Pull request merged**
