### PR TITLE
French translation and small changes to english strings.

### PR DESCRIPTION
**Pull request by mdmk**

### CODE REVIEW

**Comment by mdmk** [comment]
Hello,
Anything wrong with my pull request?
Would you prefer separate pull requests for the two commits?

**Comment by alexbakker** [comment]
Sorry for the delay here. I agree with the English changes, but we need to find someone who can verify the French translation.

**Comment by mdmk** [comment]
No problem.
Thanks for the feedback.

**Comment by michaelschattgen** [comment]
Thanks for your work @mdmk and sorry for the long wait!

**Pull request merged**
