### PR TITLE
Changed the Chip to match the background in Amoled and Dark Mode, Adjusted the Bottom Buttons

### PR DESCRIPTION
**Pull request by Hacker437**
Old Group Dialog
 

New Dialog with button alignment and new styled chips

### CODE REVIEW

**Comment by Hacker437** [comment]
@alexbakker Any suggestions please say

**Comment by alexbakker** [comment]
@Hacker437 I'll review this tomorrow.

**Review by alexbakker — CHANGES_REQUESTED** [review]
The background changes for dark and AMOLED mode look good. But I think the rest of the appearance of the chips and the bottom buttons looked fine the way they were before. Could you revert those changes?

**Comment by Hacker437** [comment]
What should I revert?

**Comment by Hacker437** [comment]
Bottom buttons?

**Comment by Hacker437** [comment]
@alexbakker Did understand What I should revert

**Comment by alexbakker** [comment]
Like I said I think the background changes on chips for dark and AMOLED mode look good. I don't really agree with the other changes.

**Comment by Hacker437** [comment]
> Like I said I think the background changes on chips for dark and AMOLED mode look good. I don't really agree with the other changes.

So you mean revert the changes for bottom buttons?

**Comment by Hacker437** [comment]
Sure,I am revert the changes tommorow

**Comment by Hacker437** [comment]
I am sorry But i messed up the branch

**Comment by Hacker437** [comment]
@alexbakker I am really Sorry for this happening for the 2nd time and i hope this wont happen again 😔😔

**Pull request closed without merging**
