### PR TITLE
Update Chinese translation.

### PR DESCRIPTION
**Pull request by Vstory**

### CODE REVIEW

**Comment by Vstory** [comment]
> Thanks! Can you remove the non-translatable strings? Please also squash your commits.


Is there a string that cannot be translated?

**Comment by alexbakker** [comment]
Yes, all of the strings with the ``translatable=false`` attribute should not appear in translation files.

**Comment by Vstory** [comment]
> Yes, all of the strings with the `translatable=false` attribute should not appear in translation files.


I'm confirming.

**Comment by Vstory** [comment]
> Yes, all of the strings with the `translatable=false` attribute should not appear in translation files.

no problem. There are 8 places without translation.
Snipaste_2020-03-18_23-47-27
Snipaste_2020-03-18_23-47-38

**Comment by Vstory** [comment]
> Thanks! Can you remove the non-translatable strings? Please also squash your commits.


Network problems, I cannot clone on the desktop.
I will close this and recreate the request.

**Pull request closed without merging**
