### PR TITLE
update Russian localization

### PR DESCRIPTION
**Pull request by andreysaksonov**

### CODE REVIEW

**Comment by michaelschattgen** [comment]
Thank you very much for your work Andrey! Just tell us when you're done with the localization and we will merge it as soon as possible.

**Comment by andreysaksonov** [comment]
@michaelschattgen it is ready

**Comment by alexbakker** [comment]
Apologies for the delay. This looks good. Can you squash your commits into a single commit?

**Comment by alexbakker** [comment]
Nevermind.

Thanks!

**Pull request merged**
