### PR TITLE
Update french translation

### PR DESCRIPTION
**Pull request by simonporte**
Update french translation and changed a word in english text.

### CODE REVIEW

**Comment by simonporte** [comment]
Hello,
What's the point with the build error ?

**Comment by alexbakker** [comment]
Did you read the error message in the [build log](https://travis-ci.org/beemdevelopment/Aegis/builds/583833788)?

```
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  /home/travis/build/beemdevelopment/Aegis/app/src/main/res/values-fr/strings.xml:123:5-76: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
      
  /home/travis/build/beemdevelopment/Aegis/app/src/main/res/values-fr/strings.xml:192:5-179: AAPT: error: unescaped apostrophe in string
      
  "Cet appareil ne supporte pas web view, qui est nécessaire pour voir l'historique des modifications. C'est un composant système manquant.".
  /home/travis/build/beemdevelopment/Aegis/app/src/main/res/values-fr/strings.xml:192:5-179: AAPT: error: not a valid string.
      
  /home/travis/build/beemdevelopment/Aegis/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-fr/values-fr.xml: error: file failed to compile.
```

**Comment by simonporte** [comment]
I tried to sqash my commits.
I failed and did obviously wrong. I'll try to correct this later.
But the build does not pass.
I corrected the unescaped ' but I don't understand this point :
`multiple substitutions specified in non-positional format`

**Comment by simonporte** [comment]
It is good this time.
There was two unescaped ' on the same line.

**Comment by alexbakker** [comment]
Thanks! One last thing: can you remove ``custom_notices_format_style`` from your translation? It's not translatable.

**Comment by simonporte** [comment]
I amended the commit to remove untranslatable string as you asked and added the 3 new strings from 445410fcd722b4b2b1a780d7b5f1c46ce08ec444.
Thanks for your patience.

**Comment by michaelschattgen** [comment]
Thank you very much for your work!

**Pull request merged**
