### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by Vstory**

### CODE REVIEW

**Comment by Vstory** [comment]
> Thanks, but this still contains strings that should not be included in translation files. Please remove them.


I didn't translate characters with "translateable =" false " ".
Why is there still a problem?

**Comment by alexbakker** [comment]
Because the whole point of setting ``translateable=" false"`` on strings is that you don't have to include them in your translation file.

**Comment by Vstory** [comment]
> Because the whole point of setting `translateable=" false"` on strings is that you don't have to include them in your translation file.

Sorry, again.

**Comment by alexbakker** [comment]
No worries. Thanks!

**Pull request merged**
