### PR TITLE
Add Python script for generating TOTP codes

### PR DESCRIPTION
**Pull request by scollovati**
Inspired by this issue https://github.com/beemdevelopment/Aegis/issues/609 and by this repo https://github.com/asmw/andOTP-decrypt I've implemented a simple python script for generating TOTP codes on a personal computer by using the Aegis encrypted vault.

### CODE REVIEW

**Comment by scollovati** [comment]
@michaelschattgen in the near future, could you spend some time in reviewing this short PR? I think that it provides to the users a simple way to using TOTP codes from a PC.

**Comment by michaelschattgen** [comment]
Yes I will. Apologies for the delay but we had some other priorities in the meantime.

**Comment by michaelschattgen** [comment]
Thank you for your pull request, it's highly appreciated. After some internal discussion we decided that the Aegis repo is not the place to maintain a CLI project like this. Initially this decrypt Python script was added to provide clarity to our vault format documentation.

We encourage you to maintain a project like this yourself if you're interested.

**Comment by scollovati** [comment]
@michaelschattgen thanks for the feedbacks. So I've created this project https://github.com/scollovati/Aegis-decrypt that allows to decrypt the Aegis vault and export its values in different formats (QR Codes with provisioning URIs included). Also it allows to generate TOTP codes on the fly.

Next steps will be to export in plain CSV, export QRCodes in a unique PDF for having a simple papaker backup and supporting other OTP formats.

**Pull request closed without merging**
