### PR TITLE
add note text field when editing entry

### PR DESCRIPTION
**Pull request by modelorona**
Reference #782 

@alexbakker I've added the note field as a string to the EditEntryActivity. It exports when the JSON option is selected.

I was wondering - maybe an info icon on the far right of the entry item could be useful. It would be shown if a note was added, and if clicked would show a popup or toast with the note. This icon could then be hid when long-pressed. Opinion?

### CODE REVIEW

**Review by alexbakker — CHANGES_REQUESTED** [review]
Thanks for working on this! A couple of suggestions:

- This introduces a second "info" icon to the view. Could you change the icon to something like: https://fonts.google.com/icons?selected=Material+Icons+Outlined:notes: instead?
- Can you make sure the Note field is always positioned above the Secret field? The positioning is currently switched if you try to add a new entry, 
- Set ``android:inputType="text|textMultiLine"`` on the Note field.

**Comment by modelorona** [comment]
Thanks for the suggestions, I'll aim to get them done this week or early next!

**Comment by alexbakker** [comment]
It looks you accidentally included the changes from some other commits (3464f93c3959e54902893f128794d8185734ef46 for example).

**Comment by modelorona** [comment]
Should be fixed now.

**Review by alexbakker — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
