### PR TITLE
Added Scroll to Group selection dialog 

### PR DESCRIPTION
**Pull request by Hacker437**
It may look like a lot of additions and subtraction but simple i did was wrap linear layout with scroll view

Reference: #755

### CODE REVIEW

**Review by alexbakker — CHANGES_REQUESTED** [review]
Can you make sure the buttons at the bottom are visible?

**Comment by Hacker437** [comment]
> Can you make sure the buttons at the bottom are visible?

Sure

**Comment by Hacker437** [comment]
> Can you make sure the buttons at the bottom are visible?

@alexbakker It looks it its difficult to implement scrolling in bottom sheet. The easiest solution to fix this is by using a dialog. What's your opinion?

**Comment by alexbakker** [comment]
Did you delete a comment? I received an email with the following:

> It looks it its difficult to implement scrolling in bottom sheet. The easiest solution to fix this is by using a dialog. What's your opinion?

What you had was working fine though. The only issue was that the buttons were not longer visible.

**Comment by Hacker437** [comment]
> Did you delete a comment? I received an email with the following:
> 
> > It looks it its difficult to implement scrolling in bottom sheet. The easiest solution to fix this is by using a dialog. What's your opinion?
> 
> What you had was working fine though. The only issue was that the buttons were not longer visible.

Yes I have deleted the comment

**Pull request closed without merging**
