### PR TITLE
Added German Translation

### PR DESCRIPTION
**Pull request by xopez**
Maybe Germans should overfly that.

### CODE REVIEW

**Comment by Wilker-a** [comment]
question: does Aegis have an instance open on [Weblate](https://hosted.weblate.com/)? i would like to help :3

**Comment by alexbakker** [comment]
@xopez

This looks good. Thanks a lot! Can you also add "German" to the language list [here](https://github.com/beemdevelopment/Aegis/blob/e6d84e68599f34db84a0c4a08e1774b59d5c04fa/app/src/main/res/values/arrays.xml#L33-L47)? (and amend that change to your initial commit)

@Wilker-a 

We're still in the process of choosing a solution for translations. In the mean while, we're happy take a PR on GitHub!

**Comment by xopez** [comment]
@alexbakker done :)

**Comment by alexbakker** [comment]
Wow, you're quick. I'll merge this, but please squash your changes next time. Thanks again!

**Pull request merged**
