### PR TITLE
Update Chinese translation.

### PR DESCRIPTION
**Pull request by Vstory**

### CODE REVIEW

**Comment by Vstory** [comment]
` Errors found:
  
  /home/travis/build/beemdevelopment/Aegis/app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java:69: Error: Format string 'delete_entries_description' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
              message = String.format(activity.getString(R.string.delete_entries_description), totalEntries);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /home/travis/build/beemdevelopment/Aegis/app/src/main/res/values-zh-rCN/strings.xml:112: This definition does not require arguments`

Error: Format string 'delete_entries_description' is not a valid format string so it should not be passed to String.format [StringFormatInvalid] 

What is the problem here?I do not understand.

**Comment by Vstory** [comment]
` 
Errors found:
/home/travis/build/beemdevelopment/Aegis/app/src/main/java/com/beemdevelopment/aegis/ui/Dialogs.java:69: Error: Format string 'delete_entries_description' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
message = String.format(activity.getString(R.string.delete_entries_description), totalEntries);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/beemdevelopment/Aegis/app/src/main/res/values-zh-rCN/strings.xml:112: This definition does not require arguments
`

Error: Format string 'delete_entries_description' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]

What is the problem here?I do not understand.

**Comment by alexbakker** [comment]
The string format verbs (like %d) should be not be translated. It looks like you translated one of those from ``%d`` to ``％d``

**Comment by Vstory** [comment]
> The string format verbs (like %d) should be not be translated. It looks like you translated one of those from `%d` to `％d`.


Thank you for your help, I learned.

**Pull request closed without merging**
