### PR TITLE
Splash Screen Implemented

### PR DESCRIPTION
**Pull request by Hacker437**
Reference For #813

### CODE REVIEW

**Review by alexbakker — CHANGES_REQUESTED** [review]
This looks really glitchy on my device. See: https://alexbakker.me/u/v4otmxmq9m.mp4.

I don't really see us merging a splash screen unless it can be made to look as good as it does on Android 12.

**Comment by krisu5** [comment]
Personally I don't like splash screens, unless they hide the loading. But Aegis is really fast app already, so it feels unnecessary.

**Comment by Hacker437** [comment]
> This looks really glitchy on my device. See: https://alexbakker.me/u/v4otmxmq9m.mp4.
> 
> I don't really see us merging a splash screen unless it can be made to look as good as it does on Android 12.

I will see about it

**Comment by lifebarier** [comment]
I agree with @krisu5 above.
Splash screen is only useful to hide loading. This app does not have any loading delay even on my old G5se.
All this would do is waste second of my time exactly when I am in a hurry to get code, and add pointless code to codebase.

This is just bloat. Please reconsider adding this.

**Comment by alexbakker** [comment]
We'll hold off on this for now.

**Pull request closed without merging**
