### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by RunningMelos**
This app is really cool! Thank you all! ! !

### CODE REVIEW

**Comment by alexbakker** [comment]
Thanks a lot!

**Comment by RunningMelos** [comment]
> action_import = 导入 ?

Yes. Import can be translated as "进口；引进；输入；说明
"(via Bing Dictionary), but usually in this case, we can translate it into "导入", which is very appropriate.

**Comment by deepseer** [comment]
> > action_import = 导入 ?
> 
> Yes. Import can be translated as "进口；引进；输入；说明
> "(via Bing Dictionary), but usually in this case, we can translate it into "导入", which is very appropriate.

抱歉，前面看错文件了。你回复的真快……
对照手机上的软件界面，我重新提出了一些修改意见
其中一部分是关于前后一致性的，比如discard和groups在几处翻译不同的问题。issuer需要更好的词但是我一时想不起来了

**Comment by RunningMelos** [comment]
哈哈哈哈，因为在摸鱼。
确实有部分翻译不太恰当（先批量机翻然后一个个修改），需要做出一定的修改。
本来想着等到中文添加进去后再仔细对比优化的，因为光看XML文件很头疼。
你有更好的翻译的话可以直接PR，趁着还没有中文版本~

**Comment by michaelschattgen** [comment]
Thanks for your contributions, I just want to let you know that we've added Aegis to Crowdin which is a translation platform. With Crowdin there is no need to manually edit our xml files.

https://crowdin.com/project/aegis-authenticator

**Pull request merged**
